Release Addon Version 16.2

diff --git a/adguardhome/bin/adguardhome_install b/adguardhome/bin/adguardhome_install
--- a/adguardhome/bin/adguardhome_install
+++ b/adguardhome/bin/adguardhome_install
@@ -40,6 +40,10 @@ ENTWARE_MONITD="${ENTWARE_ETC}/monit.d"
 # 设置自定义变量PRIVATE_ROOT为此程序根目录
 PRIVATE_ROOT="${SBL_SYS_USR}/adguardhome"
 #
+# PRIVATE_ALTERNATIVE: The directory which contains all the alternatives
+# 设置自定义变量PRIVATE_ALTERNATIVE为此程序备用文件目录
+PRIVATE_ALTERNATIVE="${PRIVATE_ROOT}/alternative"
+#
 # PRIVATE_BIN: The directory which contains all the executable files related to this program
 # 设置自定义变量PRIVATE_BIN为此程序可执行文件目录
 PRIVATE_BIN="${PRIVATE_ROOT}/bin"
@@ -98,6 +102,10 @@ ADMINUSER="$(nvram get sbl_username)"
 # 设置环境变量ADMINPASSWORD为路由器管理页面的登陆密码
 ADMINPASSWORD="$(nvram get sbl_password)"
 #
+# DNS_PORT: Local port of DNS service from ADGUARD-HOME
+# 设置自定义变量DNS_PORT为ADGUARD-HOME的DNS服务监听端口
+DNS_PORT="2153"
+#
 ########## END ##########
 #
 #
@@ -126,20 +134,32 @@ then
         # 删除遗留的adguardhome包
         /opt/bin/rm -f "${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz"
         #
-        # Download adguardhome package
-        # 下载adguardhome包
-        /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P "${PRIVATE_BIN}" "${DOWNLOAD_LINK}"
-        #
-        # Check if ${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz exists
-        # 检查文件${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz是否存在
-        if [ ! -s "${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz" ]
+        # Check if ${PRIVATE_ALTERNATIVE}/version exists
+        # 检查文件${PRIVATE_ALTERNATIVE}/version是否存在
+        if [ -e "${PRIVATE_ALTERNATIVE}/version" ]
         then
-            /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
-            /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+            # Prepare to install offline
+            # 准备离线安装
+            LATEST_VERSION="$(/opt/bin/head -n 1 "${PRIVATE_ALTERNATIVE}/version")"
+            /opt/bin/cp -f "${PRIVATE_ALTERNATIVE}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz" "${PRIVATE_BIN}"
             #
-            /opt/bin/rm -f "${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz"
+        else
+            # Download adguardhome package
+            # 下载adguardhome包
+            /opt/bin/wget-ssl -c -t 10 -T 120 --no-cookies --no-check-certificate -P "${PRIVATE_BIN}" "${DOWNLOAD_LINK}"
             #
-            exit 5
+            # Check if ${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz exists
+            # 检查文件${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz是否存在
+            if [ ! -s "${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz" ]
+            then
+                /opt/bin/echo -e "($(basename $0)): $$ \033[1;43;31mNOTICE\033[0m: CONNECTION FAILED"
+                /opt/bin/echo -e "($(basename $0)): $$ \033[1;41;37mFAILURE\033[0m: ${SERVICE_FUNCTION} ${SERVICE_NAME}"
+                #
+                /opt/bin/rm -f "${PRIVATE_BIN}/AdGuardHome_${OPERATING_SYSTEM}_${ROUTER_ARCHITECTURE}.tar.gz"
+                #
+                exit 5
+            fi
+            #
         fi
         #
         # Unzip adguardhome package
@@ -159,13 +179,22 @@ then
         /opt/bin/echo -e "bind_host: 0.0.0.0\nbind_port: 14711" > "${PRIVATE_ETC}/AdGuardHome.yaml"
         ADMINPASSWORD_ENCRYPTED="$(/opt/bin/bcrypt-tool hash "${ADMINPASSWORD}" 10)"
         /opt/bin/echo -e 'users:\n- name: '"${ADMINUSER}"'\n  password: '"${ADMINPASSWORD_ENCRYPTED}"'' >> "${PRIVATE_ETC}/AdGuardHome.yaml"
-        /opt/bin/echo -e "dns:\n  bind_host: 0.0.0.0\n  port: 2153" >> "${PRIVATE_ETC}/AdGuardHome.yaml"
+        /opt/bin/echo -e "dns:\n  bind_host: 0.0.0.0\n  port: ${DNS_PORT}" >> "${PRIVATE_ETC}/AdGuardHome.yaml"
         /opt/bin/echo -e "  bootstrap_dns:\n  - 9.9.9.9\n  - 149.112.112.112" >> "${PRIVATE_ETC}/AdGuardHome.yaml"
         /opt/bin/echo -e "  upstream_dns:\n  - 114.114.114.114" >> "${PRIVATE_ETC}/AdGuardHome.yaml"
         #
         # Create directory ${PRIVATE_VAR}
         # 创建目录${PRIVATE_VAR}
         /opt/bin/mkdir "${PRIVATE_VAR}"
+        #
+        # Configure dnsmasq.d
+        # 配置dnsmasq.d
+        if [ ! -d "${PRIVATE_ETC}/dnsmasq.d" ]
+        then
+            /opt/bin/mkdir "${PRIVATE_ETC}/dnsmasq.d"
+        fi
+        #
+        /opt/bin/echo -e "server=127.0.0.1#${DNS_PORT}" > "${PRIVATE_ETC}/dnsmasq.d/adguardhome.conf"
         #
         # Configure monit
         # 配置monit
